// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBICJjVKor0qR4ocKvsPt8hgjdX41ockj8',
    appId: '1:583527496682:web:0f58df294e06a18b319093',
    messagingSenderId: '583527496682',
    projectId: 'parking-bd17e',
    authDomain: 'parking-bd17e.firebaseapp.com',
    storageBucket: 'parking-bd17e.firebasestorage.app',
    measurementId: 'G-NX71N6749R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMFIgfNsMTMH8ZW0HIeYWWvqPE0Ty88AI',
    appId: '1:583527496682:android:bea83e542bcbfc22319093',
    messagingSenderId: '583527496682',
    projectId: 'parking-bd17e',
    storageBucket: 'parking-bd17e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcPq1IOayjl6RlByU2cxz3Bqczz_T-ldo',
    appId: '1:583527496682:ios:31d1b9f5073bde2b319093',
    messagingSenderId: '583527496682',
    projectId: 'parking-bd17e',
    storageBucket: 'parking-bd17e.firebasestorage.app',
    iosBundleId: 'com.example.parking1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcPq1IOayjl6RlByU2cxz3Bqczz_T-ldo',
    appId: '1:583527496682:ios:31d1b9f5073bde2b319093',
    messagingSenderId: '583527496682',
    projectId: 'parking-bd17e',
    storageBucket: 'parking-bd17e.firebasestorage.app',
    iosBundleId: 'com.example.parking1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBICJjVKor0qR4ocKvsPt8hgjdX41ockj8',
    appId: '1:583527496682:web:e4f0471a42531b17319093',
    messagingSenderId: '583527496682',
    projectId: 'parking-bd17e',
    authDomain: 'parking-bd17e.firebaseapp.com',
    storageBucket: 'parking-bd17e.firebasestorage.app',
    measurementId: 'G-EJMNM6KWPK',
  );
}
